name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
        docker image build -t ${{ secrets.DOCKER_USER  }}/premier_league:1.0 .
        docker push ${{ secrets.DOCKER_USER }}/premier_league:1.0 
